services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: jcred
      POSTGRES_PASSWORD: jcred
      POSTGRES_DB: jcred
    ports:
      - "5432:5432"
    volumes:
      - jcred_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jcred"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgres://jcred:jcred@db:5432/jcred
      JWT_ACCESS_SECRET: change-me-access-secret
      JWT_REFRESH_SECRET: change-me-refresh-secret
      VAULT_ENCRYPTION_KEY: ZGV2LW9ubHktMzItYnl0ZS1rZXktZG8tbm90LXVzZSE=
    ports:
      - "4000:4000"

volumes:
  jcred_pgdata:
